name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    
    - uses: rojo-rbx/rokit
      name: Install Rokit
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Lint
      run: selene ./src