# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
lune = "lune-org/lune@0.8.9"
rojo = "rojo-rbx/rojo@7.4.4"
selene = "Kampfkarren/selene@0.28.0"
luau-lsp = "johnnymorganz/luau-lsp@1.41.0"
darklua = "seaofvoices/darklua@0.16.0"
stylua = "johnnymorganz/stylua@2.0.2"
