name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install Rokit
        run: |
          curl -fsSL https://github.com/rojo-rbx/rokit/releases/latest/download/rokit-linux.tar.gz | tar xz
          sudo mv rokit /usr/local/bin/

      - name: Install Selene
        run: |
          curl -fsSL https://github.com/Kampfkarren/selene/releases/latest/download/selene-linux.zip -o selene.zip
          unzip selene.zip
          sudo mv selene /usr/local/bin/
          rm selene.zip

      - name: Lint
        run: selene ./src
