name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master



jobs:
  lint:
    name: Lint
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4



    - name: Lint
      shell: bash
      run: |
        selene ./src
