name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - uses: rojo-rbx/rokit
      name: Install Rokit
      with:
        version: "^1.0.0"
    
    - name: Verify Rokit Installation
      run: rokit --version || echo "Rokit installation failed"
      
    - name: Install Selene
      run: rokit install selene || echo "Selene installation failed"
    
    - name: Lint
      run: |
        selene src
