name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: CompeyDev/setup-rokit@v0.1.2
      with:
        version: v1.0.0
      run: selene --version
    
    - name: Checkout Repository
      uses: actions/checkout@v4
    
      
